<?php
/**
 * Prints a custom link that takes an array of items the same as what is generated by the acf link field
 *
 * @package underscores
 */

defined( 'ABSPATH' ) || exit; // Exit if accessed directly.

if ( ! function_exists( 'underscores_acf_link' ) ) :
  /**
   * Prints a custom link that takes an array of items the same as what is generated by the acf link field
   *
   * @param array $args Array of properties to pass to the button
   */
  function underscores_acf_link( array $args = [] ) {
    if ( ! is_array( $args ) ) {
      trigger_error('Expects underscores_acf_link() to receive an array', E_WARNING);
    }

    if ( ! empty( $args) ) {
      $target = $args['target'] ? 'target="'. $args['target'].'"' : '';

      echo "<a class='btn' href='{$args['url']}' {$target}>{$args['title']}</a>";
    }
  }
endif;